## Configuration for Alacritty, the GPU enhanced terminal emulator.
## Created by Aditya Shakya (@adi1090x)

## It's a very basic and simple config file, for full configuration...
## See, /usr/share/doc/alacritty/example/alacritty.yml

## Import files (Colors, Fonts, Etc)
import:
  - ~/.config/alacritty/colors.yml
  - ~/.config/alacritty/fonts.yml

## Set environment variables
env:
  TERM: alacritty

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 25

  padding:
    x: 0
    y: 0

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
background_opacity: 0.6

## Cursor
cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true

key_bindings:
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: Key0,     mods: Command, action: ResetFontSize                }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                   }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }
