# Font confiosevkaiguration
font:
  # Normal (roman) font face
  normal:
    family: "Scientifica"
    style: regular

  # Bold font face
  bold:
    family: "Scientifica"
    style: Bold

  # Italic font face
  italic:
    family: "Scientifica"
    style: Bold Italic

  # Bold italic font face
  bold_italic:
    family: "Scientifica"
    style: Bold Italic

  # Point size
  size: 10

  # Offset
  offset:
    x: 0
    y: 0

  # Glyph offset
  glyph_offset:
    x: 0
    y: 0
